version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15-openssl
    container_name: mosquitto
    restart: always
    networks:
      - otel-app-java
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
networks:
  otel-app-java: