version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15-openssl
    container_name: mosquitto
    restart: always
    networks:
      - otel-app-java
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.75.0
    container_name: opentelemetry-collector
    volumes:
      - ./config/collector/config.yml/:/etc/opentelemetry-collector.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    networks:
      - otel-app-java
    ports:
      - 4317:4317
      - 13133:13133
      - 8889:8889
    stop_grace_period: 1s

  jaeger:
    image: jaegertracing/all-in-one:1.44.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - otel-app-java
networks:
  otel-app-java: